### ISSUE TITLE
Add support for time dependent ECal gain calculations

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#100]
Data needs to go into the conditions system.

**Comment by mholtrop** [comment]
From Sebouh:
Issue 100:  I've implemented some code to run the time-dependent corrections to the Ecal gains, basically scaling the energy of the hits by a time-dependent factor, to account for how exposure to radiation affects the sensitivity of the Ecal crystals.  After a few hours, the sensitivity reaches a steady value, but in the first few hours of exposure (after the beam has been off for a while) the readout values on the Ecal are smaller than they would normally be.  This was a low-priority task, since we don't use the Ecal energy measurement in calculating the pair-mass in the bump-hunt nor the vertex search, and only a small fraction of our data is effected by this time-dependent effect.

**Comment by mholtrop** [comment]
No one available now to do this.
