### ISSUE TITLE
Track parameter and covariance propagation 

### ISSUE THREAD

**Issue by bloodyyugo** [JeffersonLab/hps-java#154]
issue for debugging the track parameter & covariance propagation and use in the vertexer

**Comment by mdiamon** [comment]
I think #158 may be part of this

**Comment by mdiamon** [comment]
my commits to this branch: you can now access the new TrackStates at Sensors using the methods in TrackStateUtils.java.  I had to make a small change for lcsim for this to work, so you have to download the latest version of it.
valid TrackStates at sensors all have location code 0... except at first sensor (which has code AtFirstHit) and last sensor (which has code AtLastHit).  there are 18 track states at sensors, consecutive in the TrackStates List.  if a track doesn't hit a sensor, the corresponding TrackState in List is invalid, and is a dummy with location code -1. 
The TrackState at the IP is still stored in the list (as the first entry, actually).
The track position at sensor is stored in the TrackState's reference point, in local (measurement) coordinates.  See TrackDataDriver.java for an example of converting this to global or tracking coords.  TrackDataDriver now uses the TrackStates at sensors, where available, to calculate residuals.

**Comment by mdiamon** [comment]
Fixed a bug in TrackUtils.extrapolateTrackUsingFieldMap that was creating TrackStates with wrong d0

**Comment by mdiamon** [comment]
my latest push to this branch requires the latest revision of lcsim (https://github.com/slaclab/lcsim/commit/1196c9f7ac21acc0d8558ad42a60469ac6099319) which I just made.  This revision makes the dummy TrackStates have sequential negative numbers (-1, -2, -3 , etc) for their location, instead of all -1; check if location<0 (instead of location==-1) to check for a dummy.  Seems silly, but is necessary to work properly with C++ LCIO (so it won't crash the DST-maker), because LCIO won't allow multiple TrackStates with the same non-zero location.

**Comment by JeremyMcCormick** [comment]
Resolved by #226.
