### ISSUE TITLE
Redesign Readout Chain to Support Hodoscope Subsystem

### ISSUE THREAD

**Issue by mccaky** [JeffersonLab/hps-java#166]
The current setup of the readout chain does not support triggering off multiple subsystems in a reasonable fashion. This needs to be corrected.

**Comment by JeremyMcCormick** [comment]
@mccaky @mholtrop 

Would it make sense to split this into two issues, one for removing or archiving the "2014" code blocks and another for adding the MC links?

You're probably going to want to cleanup the code by removing the legacy sections first, get that merged in, and then move on to adding the MC links.  Just removing the old code should be pretty straightforward, and you should also see no changes at all in the output from doing this.

Adding the MC links seems like a separate task from this, which is why I suggest splitting up this issue.

**Comment by mholtrop** [comment]
I agree, that seems like a reasonable way to move this forward more quickly.
@JeremyMcCormick do you have a good idea how to tag the legacy code so someone later can find it?

**Comment by JeremyMcCormick** [comment]
>  do you have a good idea how to tag the legacy code

Just a standard git annotated tag should be fine.

**Comment by JeremyMcCormick** [comment]
Alright, I changed this issue to be removal of the 2014 legacy code, and I made a new issue #181 for the MC relations/links.

**Comment by mholtrop** [comment]
Seems this task was merged with #418 iss166 merge.
