### ISSUE TITLE
fix in the maxTrackChisq cut, and maxTrackChisq6hits value should be changed in the steering file

### ISSUE THREAD

**Issue by rafopar** [JeffersonLab/hps-java#382]
if (!maxTrackChisq.containsKey(nhits)) { 
should be changed to 
if (!maxTrackChisq.containsKey(dof)) {

and <maxTrackChisq6hits> 72. </maxTrackChisq6hits>
should be changed to
<maxTrackChisq6hits> 84. </maxTrackChisq6hits>

**Comment by mdiamon** [comment]
Resolved by PR #383

**Comment by mdiamon** [comment]
@JeremyMcCormick pointed out, the way some of the StandardCuts setters work is "bad form": the setter methods called by the steering files should just be one-line "dummies".  I have also seen it is easy to accidentally re-set StandardCut values from multiple places in the code, when this behavior is actually undesirable (we only want them set once, at the beginning.)
I have changed the form of the setters, and also made _all the values that do not involve chi2_ settable away from their defaults _only once_ (i.e. if you set them in the steering file, changing them elsewhere in the driver has no effect.) The chi2 (and chi2 probability) values can be reset elsewhere in the driver, since the quality decisions may need to be flexible.

**Comment by mdiamon** [comment]
Resolved by PR #386
