### ISSUE TITLE
Hard-code run-by-run beamspot x-y coordinates for 2016 Pass2 reconstruction

### ISSUE THREAD

**Issue by normangraf** [JeffersonLab/hps-java#387]

**Comment by JeremyMcCormick** [comment]
Why not use the conditions database for this?  It would not be difficult and would be far more flexible.

**Comment by mholtrop** [comment]
Basically because no body feels confident in how to use it. I don’t know of a good place to learn it either. Would you have some pointers, or examples, or a document I can look at?
I have absolutely no time to go “dig through the code” and “figure it out”, though I know that with a day or so I could do it.

**Comment by JeremyMcCormick** [comment]
If someone provides me the data I can just add the necessary classes, etc.
myself.

Our confluence has pretty good documentation on how the conditions system
works but it is faster if I just do it.

**Comment by mholtrop** [comment]
I think Norman will collect the info from Matt. 
I will try to make a point of going through the confluence pages, and learning about this, because the DB stuff keeps coming up.

Thanks for volunteering. I added Norman to CC to make sure he sees this.

**Comment by JeremyMcCormick** [comment]
Someone provide me the data and I will add the classes and data for this...should take about 15 minutes.  ;-)

**Comment by JeremyMcCormick** [comment]
This should be resolved.
