### ISSUE TITLE
Update the hodoscope geometry to not have a compound object subtracted from another

### ISSUE THREAD

**Issue by mholtrop** [JeffersonLab/hps-java#389]
Minor change in the ordering of the hodoscope support arm. This makes the volume addition/subtraction more linear.

**Comment by mccaky** [comment]
@mholtrop @JeremyMcCormick 
I see that that this task is assigned to me, but I'm not entirely certain what it is for. There was some extraneous code left over in `org.lcsim.geometry.compact.converter.lcdd.Hodoscope_v1` that included a `BooleanSolid` from an early test attempt to model the holes in the scintillators. I have removed this and committed it as a change to this branch.

However, I don't think that was a part of the support arm. I believe that Maurik designed the support structure for the hodoscope, so if there is a compound object there that should be fixed, it should probably be assigned to him. Otherwise, if that extra code was the problem, then this should be ready to merge.

**Comment by JeremyMcCormick** [comment]
I have no idea.  I didn't create this issue (ask Maurik?).

**Comment by JeremyMcCormick** [comment]
Old issue - closing until someone actually will work on it.
