### ISSUE TITLE
Hodoscope Data Calibration Tools

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-java#482]
Clarify how Hodoscope calibrations will be obtained in real data.

Create and validate driver chain to perform calibrations.

**Comment by mholtrop** [comment]
Duplicates #473

**Comment by mccaky** [comment]
I'm not sure that this is a duplicate - we have (had?) several default values programmed into the conditions database for the hodoscope readout/recon. I created iss473 because we really should get all of the final, hardware-derived values plugged in rather than using default ones. This is not the same as creating a formalized process for acquiring said values. The two issues are closely related, though, and could potentially be merged.

**Comment by JeremyMcCormick** [comment]
I had made an issue (and maybe a dup) for having calibration codes in
hps-java which Rafo said he would eventually do.  But if it is fine to have
the codes in C++ I don't have any problem with it.  Just need some doc
about how to use them to produce the txt files for loading into the db.

**Comment by JeremyMcCormick** [comment]
Old issue
