### ISSUE TITLE
Fix broken readout steering files.

### ISSUE THREAD

**Issue by mholtrop** [JeffersonLab/hps-java#487]
The steering files (specifically PhysicsRun2016TrigPairs1.lcsim, but probably others as well) are referring to incorrect locations of the drivers.

**Comment by JeremyMcCormick** [comment]
Just to be clear, those are readout simulation steering files, not recon, correct?

**Comment by mccaky** [comment]
Some of the naming changes in iss420 didn't carry over properly. I'm fixing it now.

Also a question, don't the unit tests run the readout? I'm surprised one of them didn't fail from this.

@JeremyMcCormick Yes, it's readout.

**Comment by mccaky** [comment]
The steering files seem to have the correct naming conventions now. Instead, I'm seeing a 'NullPointerException' in the SVT driver, which is strange and unexpected since this driver has not really been changed since iss166. The most recent merges were all hodoscope-related and only altered its drivers and the calorimeter. I am investigating this.

[Edit] - Nevermind - I'm using the hodoscope NO TRACKER detector model, so of course the SVT driver fails. Ignore this. It doesn't happen with a model that actually has the SVT.

**Comment by mccaky** [comment]
The fixes seem to be working. Pull request #489 is now up to merge the fixes into master.

**Comment by mccaky** [comment]
Merged and closed.
