### ISSUE TITLE
Java GBL should be a standalone package

### ISSUE THREAD

**Issue by omar-moreno** [JeffersonLab/hps-java#55]

**Comment by JeremyMcCormick** [comment]
Why? :)

**Comment by omar-moreno** [comment]
So it can eventually be merged with the standard GBL option.

**Comment by JeremyMcCormick** [comment]
@normangraf @omar-moreno @mdiamon 

I have many concerns with going in this direction:

- It would introduce another external Maven module that you are depending on, so now you have to compile it before building hps-java if you want to make changes.

- If you are working from a snapshot of the new GBL module, then it has to be released before hps-java itself can be released to resolve the dependency.

- Should you want to modify and improve the GBL code, then you are going to want to do it on branches, which means then that potentially hps-java itself will need to work with those branches, which is an added complexity.  Right now, you could just do this on one hps-java branch.

- Assuming that the goal here is eventually having this binding to be maintained by the GBL project, I actually think this is potentially not a good situation, because you may lose the ability to make updates to the code as well as release versions of it when needed.

I'm not really convinced we actually get much out of pulling this code from hps-java into some separate repo.  And the likelihood that the GBL maintainers would actually then integrate this into the main GBL project and also then support it seems pretty low to me.  

So perhaps this is not actually something we should do?

**Comment by JeremyMcCormick** [comment]
Closing for now.  We have no plans to do this.
