### ISSUE TITLE
Replace gbl.Matrix with Jama.Matrix

### ISSUE THREAD

**Issue by omar-moreno** [JeffersonLab/hps-java#720]
Looks like gbl.Matrix is a copy of Jama.Matrix.  In fact, it looks like there is some functionality missing from gbl.Matrix that would be useful to have.  I propose removing it in favor of just pulling in Jama as a dependency.

**Comment by omar-moreno** [comment]
Will also check compare the performance of Jama.Matrix to Jeigen.

**Comment by normangraf** [comment]
The package is subtly different and was modified when the Java port of GBL was standalone.
Since we are planning to drop GBL in the near future I would put this on the back burner.
As for Jeigen, since it is not pure Java it opens up a whole set of platform-dependent issues that need to be balanced against any gains in raw CPU performance.

**Comment by omar-moreno** [comment]
At this point we should focus on performance.  It's not going to matter if hps-java is cross-platform if you can't run the reconstruction of the 2019 dataset in a reasonable amount of time.

**Comment by normangraf** [comment]
I concur. My point is why spend time improving code we don't intend to run on the 2019 production reconstruction?
