### ISSUE TITLE
Fix wrongly placed hits in thin sensors and remove strip 0 and 511 from the clustering

### ISSUE THREAD

**Issue by pbutti** [JeffersonLab/hps-java#785]
Observed a number of hits in the thin sensors that are placed in the wrong locations. 
This showed up clearly in Kalman Tracking routines (originally reported by Robert) 

A dump can be seen here.

PF::Debug::Sensor Name=module_L1t_halfmodule_stereo_sensor0
[ RawHitChecker ] - hit_strip=510
[ RawHitChecker ] - hit cellID=8766028252161
[ RawHitChecker ] - electrode nAxes:2
[ RawHitChecker ] - electrode getNCells:510
[ RawHitChecker ] - electrode getNRows:255
[ RawHitChecker ] - electrode getNColumns:2
[ RawHitChecker ] - electrode getPosition:[      7.0400,      22.500,      0.0000]
[ RawHitChecker ] - striplet  getRowNumber:255
[ RawHitChecker ] - striplet  getColumnNumber:2
[ RawHitChecker ] - striplet  getStripCenter:[      7.0400,      22.500,      0.0000]
[ RawHitChecker ] - striplet  getStripLength:15.0

The columnNumber is wrong (2), should be 1
The position is wrong u should be negative close to -7mm and v should be 7.5mm 
This affects strip 510 (strip 1, 2 and 509 have been checked and are OK) 

Also remove strip 0 and 511 (unbonded strip) from the clustering algorithm.

**Comment by pbutti** [comment]
Adding @omar-moreno to the thread. Working on restoring 0-509 mapping.
0-511 already removed in the clusterer.

**Comment by omar-moreno** [comment]
The solution here is to add a channel map offset parameter to SiStriplets so the cell ID's in the thin sensors match those in data. 

Currently, SiStriplets assumes the cell ID's to range from 0 - 509.  In data, because channel 0 and 511 are disconnected, the cell ID ranges from 1 - 510. Adding the channel offset in SiStriplets allows for 
1) Cell ID of MC hits to match data and not be offset by 1.  This is needed in order to get the correct conditions from the DB. 
2) Allows for the correct u-v position calculation from the cell ID's in data. At the moment, positions will be shifted by 55 um (strip pitch). 
3) Allow us to mask out channels 0 and 511 in data without impacting the simulation.  Currently, only channel 639 is masked out during the clustering stage.
