### ISSUE TITLE
Open up delta time cut for creating Si clusters

### ISSUE THREAD

**Issue by cbravo135** [JeffersonLab/hps-java#977]
The current configuration of the reconstruction uses an 8 ns time cut, and it has been shown in meetings that this is clearly too small.

**Comment by normangraf** [comment]
Details of a recent analysis can be found at https://indico.slac.stanford.edu/event/7857/contributions/5684/attachments/2593/7433/20230404_SVT_HitsAndTiming_II_ReconAnalysisWeeklyMeeting_Graf.pdf

The proposal is to open this timing window from 8ns to 20ns, where the time peak is essentially baseline resolved. 

This can be done in the steering file as follows:

```
<driver name="TrackerHitDriver" type="org.hps.recon.tracking.DataTrackerHitDriver">
            <neighborDeltaT>20.0</neighborDeltaT>
...
</driver>
```

The consequences of doing this are:

No net change in number of tracks, since hits are neither lost nor gained. 

Hits on the track which once were single strip hits now become two-strip hits.

As a result, the track momentum measurement is slightly improved.

However, the track chi-squared is increased. This provides further evidence for systematic issues with the position and/or resolution determination of multi-strip hits.

The 20ns window should be revisited when and if substantial improvements are seen in the individual strip time measurements resulting from better fits to the APV25 waveforms.

**Comment by cbravo135** [comment]
The study shown in those slides is a low lumi FEE run, so we should open it a bit more since high lumi data has a bit worse time resolution.
